name: Windows Tests
on:
  workflow_dispatch:
    inputs:
      suite:
        description: Which tests to run
        type: choice
        options: [unit, integration, all]
        required: true
      pr:
        description: PR number to comment on (optional)
        required: false

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: windows-tests
  cancel-in-progress: true

jobs:
  run:
    runs-on: [self-hosted, windows, windows-test]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Ensure toolchain
        shell: pwsh
        run: |
          $ProgressPreference='SilentlyContinue'
          # Example tooling; replace for your stack
          choco install visualstudio2022buildtools --yes --no-progress --limit-output --ignore-checksums

      - name: Run tests
        shell: pwsh
        run: |
          ./scripts/invoke-tests.ps1 -Suite '${{ inputs.suite }}' -Out "$env:RUNNER_TEMP\out"

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: windows-test-results
          path: ${{ env.RUNNER_TEMP }}\out\**

      - name: Report back to PR (optional)
        if: ${{ inputs.pr != '' }}
        env:
          GH_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
        shell: pwsh
        run: |
          gh pr comment ${{ inputs.pr }} --body "✅ Windows tests finished. Artifacts: **windows-test-results**"
